esphome:
  name: dht1
  platform: ESP8266
  board: huzzah
  # on_boot:
  #   priority: -10
  #   then:
  #     - switch.turn_off: led

wifi:
  ssid: "ssid"
  password: "pwd"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Dht1 Hotspot"
    password: "password"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
# api:
#   password: "sparkle"

ota:
  password: "sparkle"
  
web_server:
  port: 80
  
mqtt:
  broker: 192.168.1.129
  username: None
  password: None

deep_sleep:
  run_duration: 30s
  sleep_duration: 10min

sensor:
  - platform: adc
    pin: VCC
    name: "Dht1 Battery"
  - platform: dht
    pin: GPIO4
    temperature:
      name: "Dht1 Temperature"
    humidity:
      name: "Dht1 Humidity"
    model: DHT11
    update_interval: 10s
    
switch:
  - platform: gpio
    pin: GPIO12
    id: led
    name: "Dht1 Led"
    
